Refactor cpp fixes in preparation for C++ autosummary extension
jbms/sphinx-immaterial pull request #116
Opened 2022-07-07 22:58 UTC by jbms

2022-07-07 23:00 UTC, 2bndy5 commented on .pylintrc
> +extension-pkg-allow-list=pydantic.dataclasses
I had to add `lxml` to this as well, but that depends on your C++ apigen implementation.

2022-07-07 23:11 UTC, 2bndy5 commented
I'm a bit confused why this is a separate PR since its geared directly for #117

2022-07-07 23:18 UTC, 2bndy5 commented
Kinda makes sense, but it seems like a complex rebasing tactic. Should this be made a draft and kept up in parallel to #117 (for as long as that's open)?

2022-07-08 00:07 UTC, jbms commented
I plan to keep the `refactor-cpp-fixes` branch (this PR) as an ancestor of `cpp-apigen` (#117).

https://github.com/jbms/sphinx-immaterial/network

I'm hoping though that this can be merged relatively soon while we still revise #117, since I don't think further revisions of #117 will require additional changes here.

2022-07-08 01:08 UTC, 2bndy5 requested changes
Thanks for splitting this up into bite sized extensions (much easier to review this way).
### Possible separate issues

I wouldn't mind seeing a new `cpp:namespace-decl` directive to actually allow documenting a namespace declaration (even if not using the upcoming `cpp.apigen` ext). I think breathe uses a modified type declaration for this.

I also noticed that `cpp:function` doesn't support exception specifications like
```cpp
void function(int n) throws(std::out_of_range);
```
While I understand that this is generally discouraged due to differences in compiler behavior, it is still part of the C++ specs.

2022-07-08 01:53 UTC, jbms commented on sphinx_immaterial/apidoc/cpp/parameter_objects.py
> +                location=param_node,
Fixed.

2022-07-08 01:53 UTC, jbms commented on sphinx_immaterial/apidoc/cpp/cpp_resolve_c_xrefs.py
> +will be resolved by `sphinx_immaterial.external_cpp_references`.
I changed this to a config option and documented it, so now users can change the pattern if they want.

2022-07-08 01:56 UTC, jbms commented
> Thanks for splitting this up into bite sized extensions (much easier to review this way).
> 
> ### Possible separate issues
> I wouldn't mind seeing a new `cpp:namespace-decl` directive to actually allow documenting a namespace declaration (even if not using the upcoming `cpp.apigen` ext). I think breathe uses a modified type declaration for this.

Yes that could be added to the C++ domain.

Separate from that, it would be nice to modify the C++ domain to suppress the nitpick reference warnings for every namespace, though.

However, I think that might be kind of annoying to monkey patch in --- maybe it can be, though.

> 
> I also noticed that the `cpp:function` directive doesn't support exception specifications like
> 
> ```c++
> void function(int n) throws(std::out_of_range);
> ```
> 
> While I understand that this is generally discouraged due to differences in compiler behavior, it is still part of the C++ specs.

I imagine this could be supported by the C++ domain easily enough.  But note that it was deprecated in C++11 and removed in C++17:

https://en.cppreference.com/w/cpp/language/except_spec

2022-07-08 03:11 UTC, 2bndy5 commented on sphinx_immaterial/apidoc/cpp/cpp_resolve_c_xrefs.py
> +will be resolved by `sphinx_immaterial.external_cpp_references`.
oh awesome!

2022-07-08 03:15 UTC, 2bndy5 commented
> I imagine this could be supported by the C++ domain easily enough. But note that it was deprecated in C++11 and removed in C++17

This is why I haven't taken the issue upstream. Still the spec compatibility can be set at build time (like tensorstore does).

2022-07-08 03:20 UTC, 2bndy5 approved these changes

2022-07-08 06:12 UTC, merged